# Generated by Django 4.2.6 on 2023-10-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nifty',
            name='CLOSE',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='CLOSE'),
        ),
        migrations.AlterField(
            model_name='nifty',
            name='HIGH',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='HIGH'),
        ),
        migrations.AlterField(
            model_name='nifty',
            name='LOW',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='LOW'),
        ),
        migrations.AlterField(
            model_name='nifty',
            name='OPEN',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='OPEN'),
        ),
    ]
