# Generated by Django 4.2.6 on 2023-10-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_nifty_close_alter_nifty_high_alter_nifty_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nifty',
            name='CLOSE',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='CLOSE'),
        ),
        migrations.AlterField(
            model_name='nifty',
            name='HIGH',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='HIGH'),
        ),
        migrations.AlterField(
            model_name='nifty',
            name='LOW',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='LOW'),
        ),
        migrations.AlterField(
            model_name='nifty',
            name='OPEN',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='OPEN'),
        ),
    ]
